/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mp2.sandbox;

import java.io.File;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import java.util.Set;

import com.google.gson.Gson;

import org.apache.commons.io.FileUtils;

public class App {
    static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        // playLog();
        // playJson();
        // playTimestamp();
        playSync();
    }

    private static void playException() {

    }

    private static void playSync() {
        new Emulator().start();
    }

    // private static void playJson() {
    // try {
    // File file = new File("some.json");
    // String s = FileUtils.readFileToString(file, "utf-8");
    // Gson gson = new Gson();
    // Content content = gson.fromJson(s, Content.class);

    // log.info("Parsed successfully!");
    // log.info("Name: {}", content.name);
    // log.info("Authors: {}", Arrays.toString(content.authors));
    // log.info("Due date: {}", content.dueDate);
    // } catch (Exception e) {
    // log.error("Some error when playing json! {}", e.getMessage());
    // }
    // }

    // private static void playTimestamp() {
    // Date date = new Date();
    // long timeMilli = date.getTime();
    // log.info("Current is {}", timeMilli);
    // log.info("date: {}", new Date(timeMilli).toString());
    // }

}
