/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mp1;

/**
 * Entrypoint of the server.
 * Instantiates and starts the server.
 */
public class App {
    private static int port = 7777;

    public static void main(String[] args) {
        new Server().start(port);
    }
}
