/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mp3.app;

import java.net.InetSocketAddress;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger log = LogManager.getLogger();

    public static void main(String[] args) {
        log.trace("MP3 App starting with args length: {}", args.length);
        boolean runAsLeader = false;
        if (args.length > 1) {
            log.fatal("Usage: \"../gradlew run\" to run as node and");
            log.fatal("       \"../gradlew run --args leader\" to run as leader");
            return;
        }
        if (args.length == 1 && args[0].equals("leader")) {
            runAsLeader = true;
        }

        if (runAsLeader) {
            log.warn("Running as leader...");
            new Node(runAsLeader).start();
        } else {
            log.warn("Running as normal node...");
            InetSocketAddress leader = new InetSocketAddress(
                    Constants.LeaderHostName,
                    Constants.JoinPort);
            new Node(leader).start();
        }
    }
}
